authors:
  Wcowin:
    name: Serendy Lin    # Author name
    description: Free and casual # Author description
    avatar: https://cdn.jsdelivr.net/gh/MapleQiAN/img_bed/md_photos/49f7174d2d337698b34f408c6aac627.jpg # Author avatar
